### ISSUE TITLE
IOs Coinbase issue

### ISSUE THREAD

**Issue by ronak248** [coinbase/coinbase-ios-sdk#14]
i have one issue in ios sdk i have put same line as which is in coinbase ios sample demo

CoinbaseErrorDomain" - code: 2

 client.getAccountsList { (Array
                :[AnyObject]!, helper:CoinbasePagingHelper!, error:NSError!) -> Void in  
            }

Error Domain=CoinbaseErrorDomain Code=2 "The operation couldn’t be completed. (CoinbaseErrorDomain error 2.)" UserInfo=0x14ede210 {response={
}, statusCode=403}

**Comment by jwitcig** [comment]
Sorry for the delayed response here, hope you were able to resolve this.
