### ISSUE TITLE
CoinbaseAccount sendAmount not working

### ISSUE THREAD

**Issue by johnny77221** [coinbase/coinbase-ios-sdk#15]
After authentication, I am able to get primary account from client object, and getBalance from account object.
but when I can sendAmount:to:completion:
the block response with null transaction and null error
what I expected is sending BTC just like on the web
I am using sandbox environment.

**Comment by 14lox** [comment]
Hi John,
Make sure you have set the correct scope / permission to allow the app to send and any other action you want to take.
Cheers, Dai

**Comment by johnny77221** [comment]
Hi, 14lox
I saw the document on coinable website (https://developers.coinbase.com/docs/wallet/permissions) described permissions on other platform, which is different from the sample permission scope(balance transactions user) in the sample project. Where can I find the permission list for mobile SDK?

Thank you.

**Comment by jwitcig** [comment]
Hope you were able to get the information you needed.
[We're deprecating the SDK](https://github.com/coinbase/coinbase-ios-sdk/commit/3548d4612c7d835a6a7b3e444d3cb3a4aef21a75), and as such, will be closing this issue.
Thank you for your contribution.
