### ISSUE TITLE
Using Sandbox with OAUTH2

### ISSUE THREAD

**Issue by hpogosyan** [coinbase/coinbase-ios-sdk#16]
How can we use the sandbox environment with OAUTH2?

**Comment by hpogosyan** [comment]
@davidvardan please keep an eye on this thread

**Comment by jsdu** [comment]
I am wondering about this too, please let me know if you found a way.

**Comment by jwitcig** [comment]
Hey all, hope we were able to get past this.
Apologies for the delayed response here, but we will be sunsetting the repo & will not be providing support going forward.

Thank you for your participation.
