### ISSUE TITLE
Podfile.lock is out of date

### ISSUE THREAD

**Issue by mickeyreiss** [coinbase/coinbase-ios-sdk#2]
It is not possible to `pod install` in the `Example` directory because [`Podfile.lock` contains `- coinbase-official (1.0)`](https://github.com/coinbase/coinbase-ios-sdk/blob/6c294c9adb6211702504eb75981a9f0d5a441a09/Example/Podfile.lock#L2). To work around, you need to run `pod update coinbase-official`.

In addition, the tests do not seem to build out of the box due to a compiler error in the `FBSnapShotTestCase` target.

**Comment by isaacwaller** [comment]
Thanks, I fixed this, couldn't reproduce at first, I think something was cached in my CoocaPods installation.
