### ISSUE TITLE
new app update messed up the authentication

### ISSUE THREAD

**Issue by imougy** [coinbase/coinbase-ios-sdk#28]
Please watch this video, it is an endless loop of doing nothing!
https://www.dropbox.com/s/7q3ua4cfkmnidgw/coinbase.mov?dl=0

**Comment by samelliott89** [comment]
Yep seconded. Seeing this too! Please fix.

**Comment by batuhanaltun** [comment]
we have same problem!

**Comment by samelliott89** [comment]
They just released an update to the iOS app (which I'm assuming is where the break is, not the SDK). Has anyone have this resolved for them?

**Comment by mihaerzen** [comment]
Is there any update on this?

**Comment by imougy** [comment]
Nop, they are busy counting the money.

**Comment by TheRyanHickman** [comment]
same problem :(

**Comment by Tjasper7** [comment]
Any update?

**Comment by mihaerzen** [comment]
Hey @isaacwaller @14lox @dai-cb @johnnycoinbase can any of you guys please respond? At least give us a sign whether this is still maintained or should we be creating our new solutions for this using web interface or sth. Thx

**Comment by jwitcig** [comment]
Hey all, I want to apologies for the lack of response here. We truly appreciate each of your contributions to this issue.
Unfortunately, we are deprecating the SDK, and as such will be discontinuing support.

Happy New Year to each of you!
