### ISSUE TITLE
Upgrade to API /v2

### ISSUE THREAD

**Issue by thangpq264** [coinbase/coinbase-ios-sdk#29]
Do you have plan upgrade SDK to use API v2?

**Comment by zackperdue** [comment]
^

**Comment by antoine20001** [comment]
+1

**Comment by maakle** [comment]
+1 You guys made 1 billion USD last year. You should have enough money to hire some developers and help the community here...

**Comment by jimijon** [comment]
++1

**Comment by jwitcig** [comment]
Hey all, unfortunately since we are [deprecating the SDK](https://github.com/coinbase/coinbase-ios-sdk/commit/3548d4612c7d835a6a7b3e444d3cb3a4aef21a75), we won't be implementing this change.

Apologies for the delayed response & thanks you for your efforts!
