### ISSUE TITLE
Adding referral to authentication call

### ISSUE THREAD

**Issue by farshadtx** [coinbase/coinbase-ios-sdk#30]
Is there any plan to add referral to OAuth call?

**Comment by imougy** [comment]
The OAuth call already has your developer secret, so in theory, they know you.  Whether they give you the referral, I don't think so.

**Comment by jwitcig** [comment]
Hi, unfortunately we will not be implementing this change as the [project is being deprecated](https://github.com/coinbase/coinbase-ios-sdk/commit/3548d4612c7d835a6a7b3e444d3cb3a4aef21a75).

Thank you for your interest.
