### ISSUE TITLE
Example not working with installed coinbase app

### ISSUE THREAD

**Issue by mihaerzen** [coinbase/coinbase-ios-sdk#31]
I tried integrating this SDK to my application but whatever I tried, it never opened the confirmation screen with installed coinbase app. It always opened the website flow. I tried it with the example and it also doesn't work. Is this an issue with the SDK or coinbase app update?

Link to a video recording to better sum up what I'm talking about: 
https://www.dropbox.com/s/lgx4tg1yruku8pj/ScreenRecording_12-03-2017%2018%3A27.MP4

**Comment by zackperdue** [comment]
You need to add in your info.plist 
LSApplicationQueriesSchemes -> Array<com.coinbase.oauth-authorize>

**Comment by mihaerzen** [comment]
@zackperdue Nice thx! I created a PR #32 where this is documented.
