### ISSUE TITLE
Non-BTC Requests

### ISSUE THREAD

**Issue by magj3k** [coinbase/coinbase-ios-sdk#33]
Is there any way to get spot prices of non-bitcoin coins like etherium and litecoin?  It seems like there is currently only support for BTC, but being able to select between ETH, BCH, BTC, and LTC would be very useful.

**Comment by Andrew-Walker** [comment]
I might be wrong but I believe other currencies are supposed to be supported already but are broken. BTC and fiat wallets seem to be the only ones that work.

**Comment by jwitcig** [comment]
My apologies for the delayed response. I hope you were able to figure out what you needed.
As we will be [deprecating the repo](https://github.com/coinbase/coinbase-ios-sdk/commit/3548d4612c7d835a6a7b3e444d3cb3a4aef21a75), we will not be looking further into this at this time.
Thank you for your involvement in the project.
