### ISSUE TITLE
Coinbase OAuth2 authorize getting response error "invalid_grant"

### ISSUE THREAD

**Issue by hsmith825** [coinbase/coinbase-ios-sdk#37]
I have followed the directions outlined here (and shown below).  The Coinable dialog opens and I link my account.  I get an email indicated my account is linked to my app.  However,, the response I get in the AppDelegate is:  Error Domain=CoinbaseErrorDomain Code=0 "invalid_grant" UserInfo={NSLocalizedDescription=invalid_grant, NSLocalizedRecoverySuggestion=}

A code sniper is as follows:
ViewController.swift
 CoinbaseOAuth.startAuthentication(withClientId: "****************", scope: "user balance", redirectUri: "com.example.flick.Auth.coinbase-oauth://coinbase-oauth", meta: nil)

AppDelegate
func application(_ app: UIApplication,
                     open url: URL,
                     options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
        if url.scheme == "com.example.flick.auth.coinbase-oauth" {
            CoinbaseOAuth.finishAuthentication(for: url, clientId: "*************", clientSecret: "**********", completion: { (result, error) in
                if error != nil {
                    // Could not authenticate.
                    print("AppDelegate, Could not authenticate, error = \(error!)")
                } else {
                    // Tokens successfully obtained!
                    // Do something with them (store them, etc.)
                    if let result = result as? [String : AnyObject] {
                        if let accessToken = result["access_token"] as? String {
                            let apiClient = Coinbase(oAuthAccessToken: accessToken)
                            print("AppDelegate, accessToken = \(accessToken)")
                            print("AppDelegate, OAuthAccessToken = \(apiClient!)")
                        }
                    }
                    // Note that you should also store 'expire_in' and refresh the token using CoinbaseOAuth.getOAuthTokensForRefreshToken() when it expires
                }
            })
            return true
        }
        else {
            return false
        }
    }

If you have questions, please contact me.

Thanks for your help!
Howard

**Comment by hsmith825** [comment]
This is the addition to the problem above.

What I expect to get are the access_token and oAuthAccessToken.  I did not get either token.

Any ideas are appreciated!
Thanks!
Howard

**Comment by MaeseppTarvo** [comment]
How did you resolve?

**Comment by hsmith825** [comment]
I had a problem with my redirect URL.

**Comment by MaeseppTarvo** [comment]
@hsmith825 Can you be more specific? I have the exact same problem.

**Comment by hsmith825** [comment]
I am not exactly certain but as I recall, I had an inconsistency between the URL indirect specified in my Coinable dashboard, the Info.plist URL types, and CoinbaseOAuth.startAuthentication(withClientId.  One thing key to my getting the APIs to work, I placed CoinbaseOAuth.startAuthentication(withClientId: in override func viewWillAppear of ViewController.

Hope this helps.
Howard

**Comment by Fonta1n3** [comment]
I had the same issue, turns out it was that my URI had some capital letters in it which needed to be changed to lower case.

it was the portion of my bundle id in the uri.

For example the "com.CoinbaseApp.Version" part of my URI needed to be changed to "com.coinbaseapp.version" in both my app delegate CoinbaseOAuth.finishAuthentication and the view controller where i call CoinbaseOAuth.startAuthentication.

Hope that helps someone.
