### ISSUE TITLE
Scopes don't match current API version.

### ISSUE THREAD

**Issue by swaterfall** [coinbase/coinbase-ios-sdk#39]
No matter what I do I get `'Scopes don't match current API version.'`

>  let permissions = "balance user send addresses"
             CoinbaseOAuth.startAuthentication(withClientId: cliendID, scope: permissions, redirectUri: authURL, meta: meta)

or

> let permissions = "wallet:accounts:read,wallet:transactions:send,wallet:transactions:read"
            CoinbaseOAuth.startAuthentication(withClientId: cliendID, scope: permissions, redirectUri: authURL, meta: meta)

Any ideas?

**Comment by jwitcig** [comment]
Hi @swaterfall, my apologies for the delayed reponse.
I hope that you were able to resolve this issue, but wanted to let you know we are [deprecating this repository](https://github.com/coinbase/coinbase-ios-sdk/commit/3548d4612c7d835a6a7b3e444d3cb3a4aef21a75).

Thank you for filing this, your contributions are greatly appreciated!
