### ISSUE TITLE
Deeplinking to coinbase app

### ISSUE THREAD

**Issue by mschonvogel** [coinbase/coinbase-ios-sdk#53]
I'd like to deep-link from my app to the coinbase app. Did you implement an URL scheme that I could use to check whether the coinbase app is installed? (via `UIApplication.sharedApplication().canOpenURL(...)`)

**Comment by jwitcig** [comment]
Hi @mschonvogel, sorry for the very delayed response here. Links to the Coinbase app should use `coinbase.com`.

Hope that helps!
