### ISSUE TITLE
Is there a bug with Requesting Money ??

### ISSUE THREAD

**Issue by tr33z0r** [coinbase/coinbase-ios-sdk#54]
Is there anyone having issues with requesting money?

https://api.coinbase.com/v2/accounts/:account_id/transactions

 I've debugged using advanced rest client and I'm still getting this error: 

{"errors":[{"id":"param_required","message":"Missing parameter: `type`"}]}

Here is the json I'm sending across (email is redacted):

{
  "type": "request",
  "to": “email@email.com”,
  "amount": "1",
  "currency": “USD”
}

**Comment by bchavez** [comment]
Hello Coinbase,

I currently maintain the C# and .NET Coinbase API library available here: https://github.com/bchavez/Coinbase

I can also confirm this is an issue with the Coinbase REST API.

The following image below shows the HTTP network traffic from the Fiddler debugging tool on Windows. Fiddler displays the results of attempting to make a "Request Money" operation on Coinbase according to the REST documentation available here: https://developers.coinbase.com/api/v2#request-money

![Fiddler_3548](https://user-images.githubusercontent.com/478118/64366305-ccedf100-cfca-11e9-8a44-9d54a4518a18.png)

As shown above, all the required parameters are specified as the API documentation describes. However, an `HTTP 400` is returned by Coinbase. 

The error is described as:
```
{"errors":[{"id":"param_required","message":"Missing parameter: `type`"}]}
```
Which doesn't make sense because the `type` parameter ***does exist*** in the HTTP request body.

Also, I've tried various `CB-VERSION` dates, and the response is still the same.

The unit test case that generated the request is as follows:

```csharp
[Test]
public async Task can_send_mony_request()
{
   var accounts = await client.Accounts.ListAccountsAsync();

   var btcAccount = accounts.Data.First(a => a.Name.Contains("BTC Wallet"));

   var requestMoney = new RequestMoney
      {
         Type = "request",
         Amount = 1,
         Currency = "BTC",
         Description = "Test request",
         To = "bchavez@gmail.com"
      };

   var moneyRequest = await client.Transactions.RequestMoneyAsync(btcAccount.Id, requestMoney);

   moneyRequest.Dump();
}
```

Thanks,
Brian


Reopened related issue posted July 25th, 2019: https://github.com/bchavez/Coinbase/issues/57

**Comment by punidramesh** [comment]
Is anyone looking into this?

**Comment by Mike-E-angelo** [comment]
> Is anyone looking into this?

But more importantly, does anyone at Coinbase _care_ anymore?  Why create an API that has very obviously broken functionality and not bother to fix it for many years now?  And here I thought PayPal was bad. 😅😭  

That $100B valuation has people already checking out... if they weren't already checked out before, that is. 🤷‍♂️

**Comment by Mike-E-angelo** [comment]
https://www.reddit.com/r/CoinBase/comments/nczfdg/coinbase_support_has_repeatedly_ignored_requests/

**Comment by Mike-E-angelo** [comment]
https://www.reddit.com/r/CoinBase/comments/ne08wp/kind_of_says_a_lot_when_nicehash_cant_get_a

**Comment by Mike-E-angelo** [comment]
https://www.reddit.com/r/CoinBase/comments/nen8ui/how_come_theres_no_way_to_call_and_talk_to/

**Comment by Mike-E-angelo** [comment]
https://www.reddit.com/r/CoinBase/comments/nh2au7/fix_your_damn_api_so_that_we_can_withdraw_our/

**Comment by Mike-E-angelo** [comment]
https://www.reddit.com/r/CoinBase/comments/nkar4v/case_06150767_hi_i_was_told_someone_will_reach/

**Comment by Mike-E-angelo** [comment]
Someone over there actually showed up to work. 😁😏
https://www.reddit.com/r/CoinBase/comments/nky5jn/positive_customer_supportthank_you/

**Comment by Mike-E-angelo** [comment]
https://www.reddit.com/r/CoinBase/comments/nqn01s/why_does_coinbase_just_close_my_support_tickets/

**Comment by Mike-E-angelo** [comment]
Personally, I just now received a reply from Coinbase "support" for a ticket that was sent April 25th.  Only 39 days, not bad.  Just kidding that is _terrible_. :P 

https://howlongagogo.com/date/2021/april/25

Not only did they not answer the question, they spelled my name wrong. 🤦‍♂️

**Comment by Mike-E-angelo** [comment]
![5bzavh](https://user-images.githubusercontent.com/2931376/120676139-c02e5380-c463-11eb-818f-b7b260be07c1.jpg)

**Comment by Mike-E-angelo** [comment]
https://www.reddit.com/r/CoinBase/comments/nsb0cw/so_coinbase_posts_about_improving_their_customer/

**Comment by Mike-E-angelo** [comment]
https://www.reddit.com/r/CoinBase/comments/nxs1dj/account_locked_for_a_month/

**Comment by Mike-E-angelo** [comment]
All the more reason to use Coinbase... if it worked. :P

https://www.theverge.com/2021/6/19/22541286/paypal-raise-seller-fees-transactions-online-payments

**Comment by pmatar28code** [comment]
> Hello Coinbase,
> 
> I currently maintain the C# and .NET Coinbase API library available here: https://github.com/bchavez/Coinbase
> 
> I can also confirm this is an issue with the Coinbase REST API.
> 
> The following image below shows the HTTP network traffic from the Fiddler debugging tool on Windows. Fiddler displays the results of attempting to make a "Request Money" operation on Coinbase according to the REST documentation available here: https://developers.coinbase.com/api/v2#request-money
> 
> ![Fiddler_3548](https://user-images.githubusercontent.com/478118/64366305-ccedf100-cfca-11e9-8a44-9d54a4518a18.png)
> 
> As shown above, all the required parameters are specified as the API documentation describes. However, an `HTTP 400` is returned by Coinbase.
> 
> The error is described as:
> 
> ```
> {"errors":[{"id":"param_required","message":"Missing parameter: `type`"}]}
> ```
> 
> Which doesn't make sense because the `type` parameter _**does exist**_ in the HTTP request body.
> 
> Also, I've tried various `CB-VERSION` dates, and the response is still the same.
> 
> The unit test case that generated the request is as follows:
> 
> ```cs
> [Test]
> public async Task can_send_mony_request()
> {
>    var accounts = await client.Accounts.ListAccountsAsync();
> 
>    var btcAccount = accounts.Data.First(a => a.Name.Contains("BTC Wallet"));
> 
>    var requestMoney = new RequestMoney
>       {
>          Type = "request",
>          Amount = 1,
>          Currency = "BTC",
>          Description = "Test request",
>          To = "bchavez@gmail.com"
>       };
> 
>    var moneyRequest = await client.Transactions.RequestMoneyAsync(btcAccount.Id, requestMoney);
> 
>    moneyRequest.Dump();
> }
> ```
> 
> Thanks,
> Brian
> 
> Reopened related issue posted July 25th, 2019: [bchavez/Coinbase#57](https://github.com/bchavez/Coinbase/issues/57)

Hello, did you finally get a solution to this? , im facing the same problem, thanks.

**Comment by Mike-E-angelo** [comment]
https://www.cnbc.com/2021/08/24/coinbase-slammed-for-terrible-customer-service-after-hackers-drain-user-accounts.html

**Comment by Mike-E-angelo** [comment]
I received an email that Coinbase Commerce will now be charging a 1% fee for using their broken API. 🤷‍♂️

**Comment by Mike-E-angelo** [comment]
https://twitter.com/Mike_E_angelo/status/1447977937853091843

**Comment by Mike-E-angelo** [comment]
https://www.cnbc.com/2021/11/09/coinbase-coin-earnings-q3-2021.html

**Comment by Mike-E-angelo** [comment]
LULZ... my comments were minimized.  Nice to see someone over there is actually alive and "cares" :P

**Comment by ispysoftware** [comment]
I think it's probably a github bot you should be thanking.
thinking about using coinbase here and a lot concerned that this issue from freaking 2019 hasn't even been responded to

**Comment by Mike-E-angelo** [comment]
Yep, I do feel bad for being such a drag, but there is a good reason why I am doing so: I am building an application on this "platform" and it has holes in it.  So, not much of a platform at all, or a stable one at that.  

In fact, I am looking at using BitPay instead now because of this issue. 😭

**Comment by Mike-E-angelo** [comment]
Looks like it's Stripe or bust:
https://twitter.com/Mike_E_angelo/status/1502328879939301382

**Comment by jwitcig** [comment]
Hey all,
I am really sorry about this having gone unaddressed. Unfortunately, we have made the decision to sunset this SDK, and will no longer be providing support going forward.

 If this is still a concern, we recommend checking out the refreshed documentation for [Coinbase Cloud](https://docs.cloud.coinbase.com/sign-in-with-coinbase/docs/api-transactions). If the new docs leave you with further questions, the developer forum there is a great place to start a discussion. You can also share feedback in the forum about anything that you think we might need to look into.

Best of luck on your endeavors!
