### ISSUE TITLE
update integration doc

### ISSUE THREAD

**Issue by dynamicswebkul** [coinbase/coinbase-ios-sdk#57]
**import CoinbaseSDK**

is not working with the latest SDK version. It imports **coinbase_official**

But in this case, it generates an error to define this **Coinbase.default** i.e.(Type 'Coinbase' has no member 'default')

Please fix this issue ASAP

**Comment by haider03366** [comment]
import CoinbaseSDK

is not working with the latest SDK version. It imports coinbase_official.

**Comment by jwitcig** [comment]
Hey all, hoping we were able to get past this. Apologies for the delayed response.

Since we're [deprecating the repository](https://github.com/coinbase/coinbase-ios-sdk/commit/3548d4612c7d835a6a7b3e444d3cb3a4aef21a75), we're going to go ahead and close this one out.
