### ISSUE TITLE
error on refresh token

### ISSUE THREAD

**Issue by soch** [coinbase/coinbase-ios-sdk#65]
I am able to authorize the app and get temp token in redirect uri code. But the call fails when it tries to call exchangeCodeForUserToken. The error is in cert pinning. 

CoinbaseSDK[error] Resource(Error): method: "POST" path: "../oauth/token" Error:
Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://api.coinbase.com/oauth/token, NSLocalizedDescription=cancelled, NSErrorFailingURLKey=https://api.coinbase.com/oauth/token}

2021-10-29 13:24:28.598306-0700 iOS Example[70546:3160838] [BoringSSL] Function nw_protocol_boringssl_input_finished: line 1436 Peer disconnected during the middle of a handshake. Sending errSSLFatalAlert(-9802) alert

Can we get the cert needed or Coinbase helps in resolving it on their server?

**Comment by soch** [comment]
Found the issue!

BaltimoreCybertrustRoot.cer is missing. Get it from latest PR and add it to Coinbase/Supporting Files/PinnedCertificates.

**Comment by jwitcig** [comment]
Hi all, thanks for the report & investigation. Unfortunately, we will be discontinuing support for `coinbase-ios-sdk`.
We would like to thank you both for your efforts & contributions to the project.
