### ISSUE TITLE
Can I still use the sdk on my iOS application even if it is deprecated?

### ISSUE THREAD

**Issue by parthgargava** [coinbase/coinbase-ios-sdk#68]
What are the disadvantages of using the deprecated ios sdk? Is there a better way to sign in into coinbase using OAuth other than using this sdk?

**Comment by jwitcig** [comment]
Hey @parthgargava,

You are free to use the deprecated SDK in its current state, but you should know that it means that we will no longer be providing support for the library. Know that there may be bugs, missing nice-to-haves, etc. For the best experience with Coinbase APIs, you should look into [Coinbase Cloud](https://www.coinbase.com/cloud).

You are also welcome to fork the repository to make your own desired changes, or utilize a fork previously made by other community members.

Best of luck with your project!
