### ISSUE TITLE
Can't run the example app

### ISSUE THREAD

**Issue by igorbarinov** [coinbase/coinbase-ios-sdk#7]
Hi!
I downloaded the example app
After installed pods using "pod install" from Example/ folder

Here is a result
"airair2:Example bis$ pod install
Analyzing dependencies
Fetching podspec for `coinbase-official` from `../`
Downloading dependencies
Installing Expecta (0.3.2)
Installing Expecta+Snapshots (1.3.2)
Installing FBSnapshotTestCase (1.6)
Installing Specta (0.2.1)
Using coinbase-official (2.1.2)
Generating Pods project
Integrating client project
airair2:Example bis$"

After I open XCode Version 6.3 (SDK 8.3) and start Example app on iPhone6 emulator
I got an error "Build Failed"
Here is a screenshot
http://monosnap.com/image/sZTR7c21AGKyI61UHqqI2nh1zgHoga

ld: library not found for -lPods-coinbase-coinbase-official
clang: error: linker command failed with exit code 1 (use -v to see invocation)

In my link binary with library section in build phases there is a red line with libPos-coinbase.a
http://monosnap.com/image/hJwLTD3iO5zCXaS9O583XTKbUSMZrD

How to fix it?
Thanks guys!

**Comment by igorbarinov** [comment]
anyone?

**Comment by pgorsira** [comment]
see here https://github.com/coinbase/coinbase-ios-sdk/issues/10

**Comment by isaacwaller** [comment]
Make sure you are using `Coinbase.xcworkspace` and not `Coinbase.xcodeproj`

**Comment by igorbarinov** [comment]
Thanks!
